CREATE TABLE public.parcels
(
  gid integer NOT NULL DEFAULT nextval('parcels_gid_seq'::regclass),
  apn character varying(50),
  apn2 character varying(50),
  state character varying(2),
  county character varying(25),
  fips character varying(5),
  sit_hse_nu character varying(30),
  sit_dir character varying(4),
  sit_str_na character varying(50),
  sit_str_sf character varying(4),
  sit_full_s character varying(80),
  sit_city character varying(50),
  sit_state character varying(4),
  sit_zip character varying(5),
  sit_zip4 character varying(4),
  sit_post character varying(4),
  land_value character varying(15),
  impr_value character varying(15),
  tot_value character varying(15),
  assmt_year character varying(4),
  mkt_land_v character varying(15),
  mkt_impr_v character varying(15),
  tot_mkt_va character varying(15),
  mkt_val_yr character varying(4),
  rec_date character varying(10),
  sales_pric character varying(15),
  sales_code character varying(12),
  year_built character varying(4),
  const_type character varying(8),
  std_land_u character varying(10),
  lot_size character varying(15),
  bldg_area character varying(15),
  no_of_stor character varying(10),
  no_of_unit character varying(10),
  bedrooms character varying(32),
  bathrooms character varying(32),
  owner character varying(50),
  owner2 character varying(50),
  ownaddress character varying(50),
  ownaddres2 character varying(50),
  ownctystzp character varying(70),
  xcoord numeric,
  ycoord numeric,
  minx numeric,
  miny numeric,
  maxx numeric,
  maxy numeric,
  shape_leng numeric,
  shape_area numeric,
  geom geometry(MultiPolygon,4269),
  CONSTRAINT parcels_pkey PRIMARY KEY (gid)
)